# Generated by Django 6.0 on 2026-01-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_excerpt_projectimage_projectsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectsection',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='excerpt',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
