# Generated by Django 6.0 on 2026-01-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='summary',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='projectimage',
            old_name='caption',
            new_name='caption_ar',
        ),
        migrations.RenameField(
            model_name='projectsection',
            old_name='body',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='projectsection',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='project',
            name='summary_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='body_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
