# Generated by Django 6.0 on 2026-01-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsection',
            options={'ordering': ['order', 'id']},
        ),
    ]
