# Generated by Django 6.0 on 2026-01-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_category_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news'),
        ),
    ]
