# Generated by Django 6.0 on 2026-01-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsimage_options_remove_newsimage_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
