# Generated by Django 6.0 on 2026-01-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsimage_options_newsimage_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_ar',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='summary',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='newsimage',
            old_name='caption',
            new_name='caption_ar',
        ),
        migrations.RenameField(
            model_name='newssection',
            old_name='body',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='newssection',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='news',
            name='summary_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newssection',
            name='body_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newssection',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
